apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: react-vite-eks-cluster
  region: ap-southeast-2

managedNodeGroups:
  - name: standard-workers-v2
    instanceType: t3.micro
    desiredCapacity: 2
    minSize: 1
    maxSize: 2
    maxPodsPerNode: 20